.babelrc, client/src/app.js, client/src/tags/homo-content.tag, package-lock.json, package.json, webpack.config.babel.js
IE 11 向けに .babelrc を設定し直しました。
* event-source-polyfill が `Object.assign` を使用しているためその前に babel-polyfill を import する
* 使用している core-js が古く、IE 11 でエラーを出していたため最新のものに変更
* .babelrc の変更に伴い webpack.config.babel.js で ES6 Modules が使えなくなったため CommonJS に変更
* もし ES6 Modules で書きたい場合は .babelrc を webpack.config.babel.js 用にして、ビルド時の Babel の設定を別で用意する必要がある
=> Update .babelrc for polyfill

bin/.travis/before_script
Create `client/dist` so deploy user owns a write permission to that directory. For further information, have a look at #16.
=> Create client/dist before the Docker container creates it in CI build

docker-compose.yml
The installation process failed to access `.git` directory and resulted in a build error.
=> Fix volumes config in docker-compose.yml

api/src/Repository/HomoRepository.php, api/tests/Case/Repository/HomoRepositoryTest.php
MySQL doesn't understand table/column names quoted by `"`.
=> Fix a bug where query was exporterd in standard SQL

client/src/tags/homo-item.tag
Currently the connection indicators (IPv4/IPv6 and HTTP/HTTPS) are always shown in the same colors. The better appearance is to show them grayed-out if its connection is failed (ERROR).
=> Fix connection indicators to be grayed-out when failed

api/src/Action/CheckAction.php, api/src/Action/ListAction.php, api/src/Providers/HomoAppProvider.php, api/src/Providers/HomoHandlerProvider.php, api/src/Providers/HomoProvider.php, api/tests/Case/Action/ListActionTest.php
Fixes errorHandler that has been changed and updates each route to accept path with and without trailing slashe like `/check` and `/check/`.
=> Fix routing and errorHandler for /check, /list, and /badge

client/conf/default.conf
Backend servers do not have to keepalive their connection because it would be inconsistent with client requests.
=> Disable keepalive in client container

api/tests/Case/Action/BadgeActionTest.php, api/tests/Case/Action/CheckActionTest.php, api/tests/Case/Action/ListActionTest.php
PHPUnit 9 deprecates `assertRegExp` and PHPUnit 10 will replace it with `assertMatchesRegularExpression `.
=> Fix assertions to handle deprecation warnings

api/composer.json, api/composer.lock
This reverts commit e86e53da9a1d65872c8bb948a9f60ee0c7cff5b3 because the current version (7.x) of illuminate/support is not compatible with phpdotenv 5.x until illuminate/support v8.x becomes GA.
=> Revert "Bump vlucas/phpdotenv from 4.1.7 to 5.0.0 in /api (#668)"

api/Dockerfile, api/Dockerfile.development, api/composer.json, api/composer.lock, api/src/Action/HealthCheckAction.php, api/src/Logging/CustomizeFormatter.php, api/src/Providers/HomoAppProvider.php, api/src/Providers/HomoHandlerProvider.php, api/src/Providers/HomoProvider.php, api/src/config.php, api/tests/Case/Action/HealthCheckActionTest.php
Application logs and router logs have been improved using Monolog (illuminate/log).
Health check failures now logs stacktraces like the following:
```
[2020-09-20 14:19:20] ERROR: PDOException: PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /var/www/html/api/vendor/illuminate/database/Connectors/Connector.php:70
Stack trace:
#0 /var/www/html/api/vendor/illuminate/database/Connectors/Connector.php(70): PDO->__construct('mysql:host=data...', 'homo', 'homo', Array)
#1 /var/www/html/api/vendor/illuminate/database/Connectors/Connector.php(46): Illuminate\Database\Connectors\Connector->createPdoConnection('mysql:host=data...', 'homo', 'homo', Array)
#2 /var/www/html/api/vendor/illuminate/database/Connectors/MySqlConnector.php(24): …
```
=> Improve logging in api

api/src/Http/NonBufferedBody.php, api/src/Providers/HomoProvider.php
Adds support for logging the size of non-buffered body.
```
172.19.0.1 - - [20/Sep/2020:14:48:25 +0000] "GET /check/ HTTP/1.1" 200 - "-" "curl/7.72.0" "-"
```
↓
```
172.19.0.1 - - [20/Sep/2020:14:47:43 +0000] "GET /check/ HTTP/1.1" 200 10468 "-" "curl/7.72.0" "-"
```
=> Support response body size in NonBufferedBody

api/Dockerfile
Follow up for #1283.
148 MB -\> 117 MB
=> Use scratch as a base image for production

api/Dockerfile
OPcache prevents PHP process from running when a container is missing `tmp` directory.
=> Fix OPcache not working in production

api/composer.lock, client/package-lock.json, client/package.json, client/webpack.config.js
Web fonts are broken as file-loader has been deprecated since css-loader v6.0.0 (#1411).
=> Migrate file-loader to assets

api/src/Action/CheckAction.php, api/tests/Case/Action/CheckActionTest.php
Some Web browsers like IE 11 store Server Sent Events by default so this PR tries to disable them.
=> Disable cache for Check API

client/conf/default.conf.template
=> Skip access log for /metrics in nginx

api/src/Providers/HomoProvider.php
GC collects `tmpfile()` and the sslkey seems to be immediately removed after the callback finishes. The new implementation prevents it because that resource is referenced by `__toString()` function in the class.
=> Ensure sslkey is available during script lifetime

api/src/Contracts/Service/Client/Response.php, api/src/config.php, api/tests/Case/Service/CheckServiceTest.php
> The alias _CURL_HTTP_VERSION_2_ was added in 7.43.0 to better reflect the actual protocol name. 
https://curl.se/libcurl/c/CURLOPT_HTTP_VERSION.html
=> Use preferred constants

README.md, api/src/Contracts/Service/CacheService.php, api/src/Contracts/Service/Client/Altsvc.php, api/src/Providers/HomoHandlerProvider.php, api/src/Providers/HomoMetricsProvider.php, api/src/Providers/HomoProvider.php, api/src/Service/CacheService.php, api/src/Service/ClientService.php, api/src/config.php, api/tests/Case/Action/BadgeActionTest.php, api/tests/Case/Action/CheckActionTest.php, api/tests/Case/Action/HealthCheckActionTest.php, api/tests/Case/Action/ListActionTest.php, api/tests/Case/Action/MetricsActionTest.php, api/tests/Case/Http/ErrorResponseTest.php, api/tests/Case/Http/Factory/ErrorResponseFactoryTest.php, api/tests/Case/Http/NonBufferedBodyTest.php, api/tests/Case/Logging/CustomizeFormatterTest.php, api/tests/Case/Middleware/AccessLogMiddlewareTest.php, api/tests/Case/Middleware/ErrorMiddlewareTest.php, api/tests/Case/Middleware/MetricsMiddlewareTest.php, api/tests/Case/Service/CheckServiceTest.php, api/tests/Case/Service/Client/AltsvcTest.php, api/tests/Case/Service/Client/ResponseTest.php, api/tests/Case/Service/ClientServiceTest.php, api/tests/Case/Service/HomoServiceTest.php, api/tests/Case/Service/Profile/MastodonProfileServiceTest.php, api/tests/Case/Service/Profile/TwitterProfileServiceTest.php, docker-compose.yml
Currently `CURLOPT_ALTSVC` suddenly consumes a lot of RAM (~1.5 GiB) and makes an entire VM unresponsive. This PR handles Alt-Svc entries to be manually cached inside Redis.
=> Manually cache Alt-Svc rather than CURLOPT_ALTSVC

Dockerfile, api/Dockerfile
Currently, the bind mounts with the same name share the same volume for cache, but it often prevented the images to be built in parallel since it broke the lock. Now parallel builds will no longer fail due to the following error:
```
Reading package lists...
E: Could not get lock /var/lib/apt/lists/lock. It is held by process 0
E: Unable to lock directory /var/lib/apt/lists/
```
=> Use unique bind mount caches between Docker images

api/Dockerfile
The primary and local IP could not retrieved in HTTP/3 if libcurl is based on v7.81.0.
=> Downgrade libcurl from 7.81.0 to 7.80.0 in /api

api/Dockerfile
Attempting to update cURL to v7.81.0 or v7.82.0, it caused a bug where IP address could not be retrieved. ngtcp2 and nghttp3 could not be updated because it won't compile when cURL is stick to v7.80.0.
=> Update OpenSSL in api

api/Dockerfile, api/composer.json, api/composer.lock, api/src/Contracts/Service/ClientService.php, api/src/Domain/Status.php, api/src/Domain/Validator/ValidationResult.php, api/src/Handlers/ErrorHandler.php, api/src/Http/ErrorResponse.php, api/src/Middleware/ErrorMiddleware.php, api/src/Service/CheckService.php, api/src/Service/ClientService.php, api/tests/Case/Action/HealthCheckActionTest.php, api/tests/Case/Handlers/ErrorHandlerTest.php, api/tests/Case/Http/ErrorResponseTest.php, api/tests/Case/Logging/CustomizeFormatterTest.php, api/tests/Case/Middleware/ErrorMiddlewareTest.php, api/tests/Case/Middleware/MetricsMiddlewareTest.php
As brainmaestro/composer-git-hooks v2.x has conflicted with illuminate/\* v9.x, illuminate/\* has not been automatically updated. Now I bumped brainmaestro/composer-git-hooks to v3.0.0-alpha.1, illuminate/\* v9.x is compatible with this project as well.
Furthermore, this PR replaces the use of true/punycode with Intl extension as it has been abandoned in favor of symfony/polyfill-intl-idn.
=> Bump illuminate/* from 8.83.27 to 9.43.0 and replace true/punycode with Intl extension in /api

docker-compose.yml
Every time a database container is recreated, another anonymous volume gets created with the current configuration. This PR aligns bind mount to point to the correct location where `postgres` image specifies.
=> Fix database persistence in docker-compose.yml

.dockerignore, api/Dockerfile
This PR updates openssl, nghttp3, ngtcp2, and curl to their latest working versions respectively. 
With curl v7.88.0, the image successfully builds but in runtime it randomly fails with `cURL error 55: select/poll returned error` possibly due to the changes in https://github.com/curl/curl/commit/71b7e0161032927cdfb4e75ea40f65b8898b3956.
=> Bump openssl from 1.1.1t+quic to 3.0.8+quic in /api

.gitignore, README.md, api/Dockerfile, compose.yaml
This PR removes IPv6-aware configurations from docker compose and Dockerfile.
For development, it is still possible to create a `compose.override.yaml` like the following:
```yaml
services:
api:
volumes:
- type: bind
source: ./api/gai.conf
target: /etc/gai.conf
networks:
default:
enable_ipv6: true
ipam:
driver: default
config:
- subnet: fd00:4545::/48
```
and create a `gai.conf` like:
```
label ::1/128 0
```
For production, it depends on to which infrastructure HomoChecker is deployed; however, container orchestrators should support bind mounts that enable more flexible overwrites.
=> Remove default IPv6-aware configuration

api/src/Service/Validator/DOMValidatorService.php
`\ErrorException` is preferred over `\RuntimeException` for explicitness.
=> Throw \ErrorException on PHP errors

api/Dockerfile
This way `/tmp` has a correct permission while not copying `/bin/mkdir`.
=> Create /tmp using mkdir from a previous stage

api/Dockerfile
Since `php:8.2.7-fpm` has been republished with bookworm-based build, the base image for api also needs updating.
=> Bump debian from bullseye-slim to bookworm-slim in /api

README.md, api/src/Providers/HomoProvider.php, api/src/Service/ActivityPubService.php, api/src/config.php, api/tests/Case/Action/ActivityPubActorActionTest.php, api/tests/Case/Service/ActivityPubServiceTest.php, bin/init, compose.yaml
This PR fixes the following error which the current implementation ends up with:
```json
{"error":"Actor https://homo.chitoku.jp:4545/actor has no 'preferredUsername', which is a requirement for Mastodon compatibility"}
```
=> Fix incompatibility with Mastodon in GET /actor

api/README.md, api/src/Action/WebFingerAction.php, api/src/Contracts/Service/ActivityPubService.php, api/src/Providers/HomoAppProvider.php, api/src/Service/ActivityPubService.php, api/tests/Case/Action/WebFingerActionTest.php, api/tests/Case/Service/ActivityPubServiceTest.php, compose.yaml
This PR implements `GET /.well-known/webfinger` endpoint for ActivityPub support.
Related: #2435
=> Add GET /.well-known/webfinger

api/Dockerfile
Bumps openssl from openssl-3.1.5-quic1 to openssl-3.1.6-quic1.
=> Bump openssl from openssl-3.1.5-quic1 to openssl-3.1.6-quic1 in /api

api/Dockerfile
Bumps openssl from openssl-3.1.6-quic1 to openssl-3.1.7-quic1.
=> Bump openssl from openssl-3.1.6-quic1 to openssl-3.1.7-quic1 in /api

.github/workflows/_update-dockerfile-by-git.yml, .github/workflows/dependencies.yml, api/Dockerfile
This PR migrates the QUIC library from ngtcp2 to OpenSSL, which effectively updates OpenSSL from 3.1.7-quic1 (quictls/openssl) to 3.3.2.
=> Migrate from ngtcp2 to OpenSSL QUIC

api/Dockerfile
Bumps nghttp3 from v1.5.0 to v1.6.0.
=> Bump nghttp3 from v1.5.0 to v1.6.0 in /api

api/Dockerfile
Bumps openssl from openssl-3.3.2 to openssl-3.4.0.
=> Bump openssl from openssl-3.3.2 to openssl-3.4.0 in /api

api/Dockerfile
This PR bumps php to 8.3.14 because #2736 cannot be merged as phpcov does not currently support php 8.4-fpm at this moment.
=> Bump php from 8.3.13-fpm to 8.3.14-fpm in /api

api/Dockerfile
Bumps nghttp3 from v1.6.0 to v1.7.0.
=> Bump nghttp3 from v1.6.0 to v1.7.0 in /api

api/Dockerfile
Bumps openssl from openssl-3.4.0 to openssl-3.4.1.
=> Bump openssl from openssl-3.4.0 to openssl-3.4.1 in /api

api/Dockerfile
Bumps nghttp3 from v1.7.0 to v1.8.0.
=> Bump nghttp3 from v1.7.0 to v1.8.0 in /api

api/src/Providers/HomoProvider.php
```
[2025-03-26 13:59:53] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (Illuminate\\Contracts\\Container\\BindingResolutionException(code: 0): Target [Illuminate\\Contracts\\Log\\ContextLogProcessor] is not instantiable while building [HomoChecker\\Middleware\\AccessLogMiddleware, Middlewares\\AccessLog, 00000000000000080000000000000000]. at /var/www/html/api/vendor/illuminate/container/Container.php:1284)
[stacktrace]
#0 /var/www/html/api/vendor/illuminate/container/Container.php(1026): Illuminate\\Container\\Container->notInstantiable('Illuminate\\\\Cont...')
#1 /var/www/html/api/vendor/illuminate/container/Container.php(890): Illuminate\\Container\\Container->build('Illuminate\\\\Cont...')
#2 …
```
=> Add `Illuminate\Log\Context\ContextServiceProvider`

api/Dockerfile
Bumps openssl from openssl-3.4.1 to openssl-3.5.0.
=> Bump openssl from openssl-3.4.1 to openssl-3.5.0 in /api

api/Dockerfile
Bumps nghttp3 from v1.8.0 to v1.9.0.
=> Bump nghttp3 from v1.8.0 to v1.9.0 in /api

api/Dockerfile
Bumps nghttp3 from v1.9.0 to v1.10.1.
=> Bump nghttp3 from v1.9.0 to v1.10.1 in /api

api/Dockerfile
Bumps openssl from openssl-3.5.0 to openssl-3.5.1.
=> Bump openssl from openssl-3.5.0 to openssl-3.5.1 in /api

api/Dockerfile
Bumps openssl from openssl-3.5.1 to openssl-3.5.2.
=> Bump openssl from openssl-3.5.1 to openssl-3.5.2 in /api

client/src/tags/homo-content.riot, client/src/tags/homo-item.riot
From Riot.js v10, attributes have to be explicitly specified in a child component.
=> Follow changes in Riot.js v10
