chitoku-k/HomoChecker

README.md

append h2o document

---

README.md

```js
content = content.replace(/h2o/, str => str.toUpperCase());
```

tweak (h2o -> H2O)

---

client/src/tags/homo-anime.tag

fix homo-anime.tag

---

client/package-lock.json
client/package.json
client/src/tags/homo-anime.tag

その他、特に意味のない最適化をしていたところを見やすくしました。

homo-anime で RxJS を使うようにした

---

api/src/Action/BadgeAction.php
api/src/Action/CheckAction.php
api/src/Action/ListAction.php
api/src/Domain/Homo.php
api/src/Domain/Status.php
api/src/Service/CheckService.php
api/src/Service/HomoService.php
api/src/Service/Profile/MastodonProfileService.php
api/src/Service/Profile/TwitterProfileService.php
api/src/Service/Validator/DOMValidatorService.php
api/src/Service/Validator/HeaderValidatorService.php
api/src/Service/Validator/URLValidatorService.php
api/src/index.php
api/tests/Case/Action/ListActionTest.php
api/tests/Case/Service/CheckServiceTest.php
api/tests/Case/Service/HomoServiceTest.php

Use PHP 7.4 features

---

README.md
docker-compose.yml

Configures to use an automatically-created network if IPv6 is not set up; otherwise, create one manually.

Update network configuration

---

client/conf/default.conf

Add /healthz endpoint

---

.dockerignore
.github/workflows/cd.yml
.github/workflows/ci.yml
Dockerfile
README.md
client/.dockerignore
client/package-lock.json
client/package.json
client/src/tags/homo-header.tag
client/webpack.config.babel.js
docker-compose.test.yml
docker-compose.yml

Updates the link to the source code in the header that it links to the exact tree in GitHub.

Link to GitHub tree in the header

---

api/Dockerfile.development

Fix #651: Use 7.4.7-fpm for php image

---

api/src/Action/BadgeAction.php
api/src/Action/CheckAction.php
api/src/Action/HealthCheckAction.php
api/src/Action/ListAction.php
api/src/Providers/HomoAppProvider.php
api/tests/Case/Action/BadgeActionTest.php
api/tests/Case/Action/CheckActionTest.php
api/tests/Case/Action/HealthCheckActionTest.php
api/tests/Case/Action/ListActionTest.php
client/conf/default.conf

The current health check did nothing meaningful for broken API releases.

Health check from API

---

.github/workflows/cd.yml

CD workflow has been broken since #781.

Fix CD workflow regression

---

client/src/tags/homo-content.tag

Fix blurring in HiDPI environment

---

client/src/styles.scss

`Yu Gothic Medium` looks much better in HiDPI environments.

Change Japanese font-family in Windows

---

README.md
api/Dockerfile
api/Dockerfile.development
api/README.md
api/src/Repository/HomoRepository.php
api/src/config.php
api/tests/Case/Repository/HomoRepositoryTest.php
bin/init
bin/lint
bin/test
client/src/tags/homo-anime.tag
database/homo.sql
docker-compose.test.yml
docker-compose.yml

We now drop MySQL and migrate to PostgreSQL.

Migrate to PostgreSQL

---

api/src/Service/Profile/MastodonProfileService.php
api/src/Service/Profile/TwitterProfileService.php

https://laravel.com/docs/5.8/releases#laravel-5.8

Fix icon cache expiration (Laravel >= 5.8)

---

api/Dockerfile

Use smaller image in production

---

Dockerfile

Not using alpine for it can potentially cause glibc problems in the future.

Use debian:buster-slim based node

---

client/src/app.js
client/src/tags/homo-content.tag

Use RxJS in homo-content component

---

api/src/Providers/HomoProvider.php

Ensure the permission for the private key is set to 0600

---

README.md
api/Dockerfile
api/README.md
api/php/ext/curl/interface.patch
api/src/Contracts/Service/Client/Response.php
api/src/config.php
client/src/tags/homo-item.tag
docker-compose.yml

Adds experimental support for HTTP/3 🎉 
Currently, HTTP/3 is enabled only when Alt-Svc cache is active.

Add support for HTTP/3 connections

---

api/src/Service/ClientService.php
api/tests/Case/Service/ClientServiceTest.php

https://datatracker.ietf.org/doc/html/rfc7838#section-5

Send Alt-Used when using Alt-Svc

---

client/conf/default.conf.template
client/conf/locations/api.conf.template
client/conf/locations/root.conf.template

This makes it easier to create an SSL server on another port.

Split nginx locations to /etc/nginx/conf.d/locations

---

api/README.md
api/src/Domain/Status.php
api/src/Service/ClientService.php
api/tests/Case/Action/CheckActionTest.php
api/tests/Case/Service/ClientServiceTest.php
client/src/tags/homo-item.tag

Enforce HTTPS when switching to HTTP/3

---

.gitignore

Unnecessarily committed. Not sure why.

Remove client/dist

---

docker-compose.yml

Update base image versions

---

api/README.md
api/phpunit.xml
api/src/Contracts/Service/Client/Response.php
api/src/Domain/Result.php
api/src/Domain/Status.php
api/src/Service/CheckService.php
api/src/Service/ClientService.php
api/src/config.php
api/tests/Case/Action/CheckActionTest.php
api/tests/Case/Service/CheckServiceTest.php
api/tests/Case/Service/Client/ResponseTest.php
client/src/tags/homo-item.tag

Add TLS certificate information 

---

api/src/Contracts/Service/Client/Altsvc.php
api/src/Contracts/Service/Client/Response.php
api/src/Service/CacheService.php
api/src/Service/ClientService.php

Available since illuminate/\* v9.x.

Remove use of Illuminate\Support\Str in favor of str()

---

api/src/Service/Profile/TwitterProfileService.php

Extend cache duration for Twitter profile images

---

api/src/Contracts/Service/ValidatorService.php
api/src/Service/Validator/DOMValidatorService.php
api/src/Service/Validator/HeaderValidatorService.php
api/src/Service/Validator/URLValidatorService.php
api/tests/Case/Service/Validator/DOMValidatorServiceTest.php

This PR fixes a regression produced in #2243.

Fix a bug where empty HTML is considered as an error

---

api/src/Providers/HomoProvider.php

This should be handled by container orchestrators.

Remove deception process on the permission for `sslkey`

---

api/Dockerfile

Useful when experimenting with HTTP/3.

Fix /usr/local/bin/{curl,openssl} to work

---

api/src/Service/ActivityPubService.php
api/tests/Case/Action/ActivityPubActorActionTest.php
api/tests/Case/Service/ActivityPubServiceTest.php

See: https://www.w3.org/TR/activitypub/#actor-objects

Implement missing properties in Actor objects

---

README.md
api/src/Http/RequestSigner.php
api/src/Providers/HomoProfileServiceProvider.php
api/src/Repository/HomoRepository.php
api/src/Service/ActivityPubService.php
api/src/config.php
api/tests/Case/Http/RequestSignerTest.php
api/tests/Case/Service/ActivityPubServiceTest.php
bin/init
compose.yaml

Retrieve Mastodon profiles with signed requests

---

client/eslint.config.js

Import eslint-plugin-riot as a plugin

---

client/package.json
client/webpack.config.mjs
client/yarn.lock

This PR complete disables eslint in the build process.

Disable eslint in build process

---

api/composer.lock

Bump dependencies in /api

---

api/Dockerfile

Bumps curl from curl-8_10_0 to curl-8_10_1.

Bump curl from curl-8_10_0 to curl-8_10_1 in /api

---

client/package.json

Bumps yarn from 4.4.1 to 4.5.0 in /client.

Bump yarn from 4.4.1 to 4.5.0 in /client

---

client/package.json

Bumps yarn from 4.5.0 to 4.5.1 in /client.

Bump yarn from 4.5.0 to 4.5.1 in /client

---

api/Dockerfile

Bumps curl from curl-8_10_1 to curl-8_11_0.

Bump curl from curl-8_10_1 to curl-8_11_0 in /api

---

client/package.json

Bumps yarn from 4.5.1 to 4.5.2 in /client.

Bump yarn from 4.5.1 to 4.5.2 in /client

---

client/package.json

Bumps yarn from 4.5.2 to 4.5.3 in /client.

Bump yarn from 4.5.2 to 4.5.3 in /client

---

api/Dockerfile

Bumps curl from curl-8_11_0 to curl-8_11_1.

Bump curl from curl-8_11_0 to curl-8_11_1 in /api

---

client/package.json

Bumps yarn from 4.5.3 to 4.6.0 in /client.

Bump yarn from 4.5.3 to 4.6.0 in /client

---

api/tests/Case/Domain/StatusTest.php

Add a test case for invalid IDN

---

api/Dockerfile

Bumps curl from curl-8_11_1 to curl-8_12_0.

Bump curl from curl-8_11_1 to curl-8_12_0 in /api

---

api/Dockerfile

Bumps curl from curl-8_12_0 to curl-8_12_1.

Bump curl from curl-8_12_0 to curl-8_12_1 in /api

---

client/package.json

Bumps yarn from 4.6.0 to 4.7.0 in /client.

Bump yarn from 4.6.0 to 4.7.0 in /client

---

client/package.json

Bumps yarn from 4.7.0 to 4.8.0 in /client.

Bump yarn from 4.7.0 to 4.8.0 in /client

---

api/Dockerfile

Bumps curl from curl-8_12_1 to curl-8_13_0.

Bump curl from curl-8_12_1 to curl-8_13_0 in /api

---

api/composer.json
api/composer.lock

See: https://github.com/illuminate/database/commit/300518186551680a37d5d727b5c335e66eb73a01

Install illuminate/http due to incompatibility since illuminate/database:12.7.0

---

client/package.json

Bumps yarn from 4.8.1 to 4.9.1 in /client.

Bump yarn from 4.8.1 to 4.9.1 in /client

---

api/Dockerfile

Bumps curl from curl-8_14_0 to curl-8_14_1.

Bump curl from curl-8_14_0 to curl-8_14_1 in /api

---

api/Dockerfile

Bumps curl from curl-8_14_1 to curl-8_15_0.

Bump curl from curl-8_14_1 to curl-8_15_0 in /api

---

client/package.json

Bumps yarn from 4.9.4 to 4.10.2 in /client.

Bump yarn from 4.9.4 to 4.10.2 in /client
